<?php

namespace LunchTime\DeliveryBundle\Entity\Menu;

use Doctrine\ORM\EntityRepository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
}