<?php

namespace LunchTime\DeliveryBundle\Entity\Menu;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function getListQuery()
    {
        $qb = $this->createQueryBuilder('i')
            ->select('i');

        return $qb->getQuery();
    }
}