<?php

namespace LunchTime\DeliveryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function getListWithItemsQuery()
    {
        $qb = $this->createQueryBuilder('m')
            ->select('m, i')
            ->leftJoin('m.items', 'i')
            ->orderBy('m.due_date');

        return $qb->getQuery();
    }

    public function getListQuery()
    {
        $qb = $this->createQueryBuilder('m')
            ->select('m');

        return $qb->getQuery();
    }
}