<?php

namespace LunchTime\DeliveryBundle\Entity\Client;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    public function getListWithItemsQuery()
    {
        $qb = $this->createQueryBuilder('o')
            ->select('o, i, m')
            ->leftJoin('o.items', 'i')
            ->innerJoin('i.menu_item', 'm')
            ->orderBy('o.due_date');

        return $qb->getQuery();
    }
}